"""Enable cascade delete on audio notes

Revision ID: 318349cda835
Revises: 2b41567d923d
Create Date: 2025-07-13 11:07:28.391633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '318349cda835'
down_revision = '2b41567d923d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_note', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audio_note_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('audio_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audio_note_ibfk_1'), 'transaction', ['transaction_id'], ['id'])

    # ### end Alembic commands ###
